<?php
// russian:русский //

$_l['more'] = 'Читати повністю';
$_l['cmnt'] = 'коментарі';
$_l['cmnto'] = 'коментар';
$_l['commentadd'] = 'Додати коментар';
$_l['commentnick'] = 'Ім’я';

$_l['notitle'] = '';
$_l['calendar_empty'] = '<center><b>Немає записів</b></center>';
$_l['anonymous'] = 'Анонімус';

$_l['subscribe'] = '<center><b>Тепер ви підписані на коментарі до запису.</b></center>';
$_l['unsubscribe'] = '<center><b>Ви більше не підписані на коментарі до запису.</b></center>';

$_l['ncikden'] = '<b><div align="center">Не можна використовувати ім’я автора.</div></b>';
$_l['cmnt_add'] = '<center><b>Коментар додано.</b></center>';

$_l['action_den'] = '<center><b>Недостатньо прав (або ви щось пропустили).</b></center>';

$_l['cmnt_add'] = '<center><b>Коментар додано.</b></center>';
$_l['cmnt_den'] = '<center><b>Коментування заборонено.</b></center>';
$_l['cmnt_addhide'] = '<center><b>Коментар додано і приховано (його побачить лише автор).</b></center>';
$_l['cmnt_attach'] = 'прикріпити файл';
$_l['cmnt_privat'] = 'приватний коментар';
$_l['cmnt_wrong_capcha'] = '<center><b>Перевірте, чи правильно ви ввели код.</b></center>';
$_l['cmnt_notxt'] =  '<center><b>Не можна додавати порожні коментарі.</b></center>';
$_l['cmnt_www'] =  '<center><b>Здається, ви неправильно ввели посилання на сайт.</b></center>';
$_l['post_notxt'] =  '<center><b>Треба ввести текст або заголовок.</b></center>';
$_l['not_found'] = '<center><b>Такої сторінки немає.</b></center>';
$_l['search_not_found'] = '<center><b>Нічого не знайдено.</b></center>';



$_l['ppp_link_next'] = 'Старіші записи &#8594;';
$_l['ppp_link_prev'] = '&#8592; Новіші записи';

// Админ-центр
$_l['admclogin'] = 'Вхід';
$_l['admclogout'] = 'Вихід';


// уведомления на мыло
$_l['link']='Посилання';
$_l['unlink']='Відписатись';


//шаблон
$_l['redirect'] = '<div align="center" style="margin: 15px 0;">Зачекайте 4 секунди...<br />(<a href=%link%>якщо не хочете, натисніть тут</a>)</div>';
?>
